name: Maigret Search Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maigret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev python3-setuptools
        python3 -m pip install --upgrade pip
        pip install maigret

    - name: Run Maigret
      run: |
        mkdir -p output
        maigret najlamsv -a --output output/results.html

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: maigret-results
        path: output/results.html
