name: Maigret Scan

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to search'
        required: true
        type: string

jobs:
  run-maigret:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Maigret
        run: |
          pip install --upgrade pip==23.3.1
          pip install maigret

      - name: Run Maigret and show output
        run: |
          maigret "${{ github.event.inputs.username }}"
