name: Run Maigret Scan

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to search'
        required: true
        type: string

jobs:
  maigret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Downgrade pip (fix Maigret install issue)
        run: |
          python -m pip install --upgrade pip==23.3.1

      - name: Install fixed version of arabic-reshaper (manual fix)
        run: |
          pip install arabic-reshaper==2.1.1

      - name: Install Maigret (older stable version)
        run: |
          pip install maigret==0.4.0

      - name: Run Maigret scan
        run: |
          mkdir output
          maigret "${{ github.event.inputs.username }}" -o output/result.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: maigret-report
          path: output/result.html
